"""Add trafik cezalari table

Revision ID: 06867c698478
Revises: e9086209810d
Create Date: 2026-01-06 13:44:38.629980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06867c698478'
down_revision = 'e9086209810d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trafik_cezalari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('arac_id', sa.Integer(), nullable=False),
    sa.Column('surucu_id', sa.Integer(), nullable=True),
    sa.Column('ceza_tarihi', sa.DateTime(), nullable=False),
    sa.Column('teblig_tarihi', sa.Date(), nullable=True),
    sa.Column('son_odeme_tarihi', sa.Date(), nullable=True),
    sa.Column('ceza_tutari', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('indirimli_tutar', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('odenen_tutar', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ceza_turu', sa.String(length=100), nullable=True),
    sa.Column('ceza_puani', sa.Integer(), nullable=True),
    sa.Column('plaka_yazilan', sa.String(length=20), nullable=True),
    sa.Column('konum', sa.String(length=200), nullable=True),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('tutanak_no', sa.String(length=50), nullable=True),
    sa.Column('belge_yolu', sa.String(length=500), nullable=True),
    sa.Column('durum', sa.String(length=20), nullable=True),
    sa.Column('odeme_tarihi', sa.Date(), nullable=True),
    sa.Column('surucuye_yansitildi', sa.Boolean(), nullable=True),
    sa.Column('yansitma_tarihi', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['arac_id'], ['araclar.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['surucu_id'], ['calisanlar.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trafik_cezalari')
    # ### end Alembic commands ###
