"""Add sozlesme module

Revision ID: 08520dd686a9
Revises: 7165106eb187
Create Date: 2026-01-04 12:17:15.360224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08520dd686a9'
down_revision = '7165106eb187'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sozlesme_tipleri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(length=100), nullable=False),
    sa.Column('kod', sa.String(length=20), nullable=True),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('uyari_gun_1', sa.Integer(), nullable=True),
    sa.Column('uyari_gun_2', sa.Integer(), nullable=True),
    sa.Column('uyari_gun_3', sa.Integer(), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('sira', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kod')
    )
    op.create_table('sozlesmeler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('baslik', sa.String(length=200), nullable=False),
    sa.Column('sozlesme_no', sa.String(length=50), nullable=True),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('tip_id', sa.Integer(), nullable=False),
    sa.Column('musteri_id', sa.Integer(), nullable=True),
    sa.Column('tedarikci_id', sa.Integer(), nullable=True),
    sa.Column('diger_taraf', sa.String(length=200), nullable=True),
    sa.Column('baslangic_tarihi', sa.Date(), nullable=False),
    sa.Column('bitis_tarihi', sa.Date(), nullable=False),
    sa.Column('imza_tarihi', sa.Date(), nullable=True),
    sa.Column('otomatik_yenileme', sa.Boolean(), nullable=True),
    sa.Column('yenileme_suresi_ay', sa.Integer(), nullable=True),
    sa.Column('tutar', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('para_birimi', sa.String(length=3), nullable=True),
    sa.Column('kdv_dahil', sa.Boolean(), nullable=True),
    sa.Column('odeme_periyodu', sa.String(length=20), nullable=True),
    sa.Column('durum', sa.String(length=20), nullable=True),
    sa.Column('sorumlu_id', sa.Integer(), nullable=True),
    sa.Column('ozel_sartlar', sa.Text(), nullable=True),
    sa.Column('notlar', sa.Text(), nullable=True),
    sa.Column('dosya_adi', sa.String(length=255), nullable=True),
    sa.Column('dosya_yolu', sa.String(length=500), nullable=True),
    sa.Column('son_uyari_tarihi', sa.Date(), nullable=True),
    sa.Column('uyari_gonderildi_30', sa.Boolean(), nullable=True),
    sa.Column('uyari_gonderildi_15', sa.Boolean(), nullable=True),
    sa.Column('uyari_gonderildi_7', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['musteri_id'], ['musteriler.id'], ),
    sa.ForeignKeyConstraint(['sorumlu_id'], ['calisanlar.id'], ),
    sa.ForeignKeyConstraint(['tedarikci_id'], ['tedarikciler.id'], ),
    sa.ForeignKeyConstraint(['tip_id'], ['sozlesme_tipleri.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sozlesme_no')
    )
    op.create_table('sozlesme_ekleri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sozlesme_id', sa.Integer(), nullable=False),
    sa.Column('baslik', sa.String(length=200), nullable=False),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('dosya_adi', sa.String(length=255), nullable=True),
    sa.Column('dosya_yolu', sa.String(length=500), nullable=True),
    sa.Column('dosya_tipi', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sozlesme_id'], ['sozlesmeler.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sozlesme_ekleri')
    op.drop_table('sozlesmeler')
    op.drop_table('sozlesme_tipleri')
    # ### end Alembic commands ###
