"""Add talep module

Revision ID: 085b6b9ed5d8
Revises: 4cd216b40c9b
Create Date: 2026-01-04 12:56:58.731300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '085b6b9ed5d8'
down_revision = '4cd216b40c9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('talep_kategorileri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(length=100), nullable=False),
    sa.Column('kod', sa.String(length=20), nullable=True),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('ikon', sa.String(length=50), nullable=True),
    sa.Column('renk', sa.String(length=20), nullable=True),
    sa.Column('varsayilan_atanan_id', sa.Integer(), nullable=True),
    sa.Column('sla_cevap', sa.Integer(), nullable=True),
    sa.Column('sla_cozum', sa.Integer(), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('sira', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['varsayilan_atanan_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kod')
    )
    op.create_table('talepler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('talep_no', sa.String(length=20), nullable=True),
    sa.Column('olusturan_id', sa.Integer(), nullable=False),
    sa.Column('kategori_id', sa.Integer(), nullable=False),
    sa.Column('konu', sa.String(length=200), nullable=False),
    sa.Column('aciklama', sa.Text(), nullable=False),
    sa.Column('oncelik', sa.String(length=20), nullable=True),
    sa.Column('durum', sa.String(length=20), nullable=True),
    sa.Column('atanan_id', sa.Integer(), nullable=True),
    sa.Column('atanma_tarihi', sa.DateTime(), nullable=True),
    sa.Column('ilk_yanit_tarihi', sa.DateTime(), nullable=True),
    sa.Column('cozum_tarihi', sa.DateTime(), nullable=True),
    sa.Column('kapatma_tarihi', sa.DateTime(), nullable=True),
    sa.Column('cozum_notu', sa.Text(), nullable=True),
    sa.Column('dosya_adi', sa.String(length=255), nullable=True),
    sa.Column('dosya_yolu', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['atanan_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['kategori_id'], ['talep_kategorileri.id'], ),
    sa.ForeignKeyConstraint(['olusturan_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('talep_no')
    )
    op.create_table('talep_yorumlari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('talep_id', sa.Integer(), nullable=False),
    sa.Column('yazan_id', sa.Integer(), nullable=False),
    sa.Column('icerik', sa.Text(), nullable=False),
    sa.Column('tip', sa.String(length=20), nullable=True),
    sa.Column('dahili', sa.Boolean(), nullable=True),
    sa.Column('dosya_adi', sa.String(length=255), nullable=True),
    sa.Column('dosya_yolu', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['talep_id'], ['talepler.id'], ),
    sa.ForeignKeyConstraint(['yazan_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('talep_yorumlari')
    op.drop_table('talepler')
    op.drop_table('talep_kategorileri')
    # ### end Alembic commands ###
