"""Icra dosyalari modeli

Revision ID: 2c7c919b2464
Revises: 4f9e7a164f63
Create Date: 2026-01-15 14:23:50.733972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c7c919b2464'
down_revision = '4f9e7a164f63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('icra_dosyalari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calisan_id', sa.Integer(), nullable=False),
    sa.Column('dosya_no', sa.String(length=100), nullable=False),
    sa.Column('icra_dairesi', sa.String(length=200), nullable=False),
    sa.Column('alacakli', sa.String(length=200), nullable=True),
    sa.Column('toplam_borc', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('kalan_borc', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('taksit_sayisi', sa.Integer(), nullable=True),
    sa.Column('taksit_tutari', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('baslangic_tarihi', sa.Date(), nullable=True),
    sa.Column('bitis_tarihi', sa.Date(), nullable=True),
    sa.Column('kesinti_orani', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('durum', sa.String(length=30), nullable=True),
    sa.Column('notlar', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['calisan_id'], ['calisanlar.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('icra_kesintileri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('icra_dosyasi_id', sa.Integer(), nullable=False),
    sa.Column('donem', sa.String(length=7), nullable=False),
    sa.Column('tutar', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('kesinti_tarihi', sa.Date(), nullable=True),
    sa.Column('durum', sa.String(length=30), nullable=True),
    sa.Column('notlar', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['icra_dosyasi_id'], ['icra_dosyalari.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('icra_kesintileri')
    op.drop_table('icra_dosyalari')
    # ### end Alembic commands ###
