"""Add onay system

Revision ID: 361e72e046a3
Revises: 395cd719da95
Create Date: 2026-01-02 12:38:12.355439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '361e72e046a3'
down_revision = '395cd719da95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Önce onay_tipleri (bağımlılık yok)
    op.create_table('onay_tipleri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kod', sa.String(length=50), nullable=False),
    sa.Column('ad', sa.String(length=100), nullable=False),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('modul', sa.String(length=50), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('sira', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kod')
    )
    
    # 2. onay_akislari (onay_tipleri'ne bağlı)
    op.create_table('onay_akislari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('onay_tipi_id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(length=100), nullable=False),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('kosullar', sa.JSON(), nullable=True),
    sa.Column('oncelik', sa.Integer(), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, default=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['onay_tipi_id'], ['onay_tipleri.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    # 3. onay_adimlari (onay_akislari'na bağlı)
    op.create_table('onay_adimlari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('akis_id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(length=100), nullable=False),
    sa.Column('sira', sa.Integer(), nullable=True),
    sa.Column('onaylayici_tipi', sa.String(length=20), nullable=False),
    sa.Column('onaylayici_rol', sa.String(length=50), nullable=True),
    sa.Column('onaylayici_kullanici_id', sa.Integer(), nullable=True),
    sa.Column('paralel', sa.Boolean(), nullable=True),
    sa.Column('tumu_onaymali', sa.Boolean(), nullable=True),
    sa.Column('otomatik_onay_sure', sa.Integer(), nullable=True),
    sa.Column('atlanabilir', sa.Boolean(), nullable=True),
    sa.Column('kosul', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['akis_id'], ['onay_akislari.id'], ),
    sa.ForeignKeyConstraint(['onaylayici_kullanici_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    # 4. yetki_devirleri
    op.create_table('yetki_devirleri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('devreden_id', sa.Integer(), nullable=False),
    sa.Column('devralan_id', sa.Integer(), nullable=False),
    sa.Column('baslangic_tarihi', sa.Date(), nullable=False),
    sa.Column('bitis_tarihi', sa.Date(), nullable=False),
    sa.Column('tum_tipler', sa.Boolean(), nullable=True),
    sa.Column('onay_tipi_ids', sa.JSON(), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('neden', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['devralan_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['devreden_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    # 5. onay_talepleri
    op.create_table('onay_talepleri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('onay_tipi_id', sa.Integer(), nullable=False),
    sa.Column('akis_id', sa.Integer(), nullable=False),
    sa.Column('referans_tablo', sa.String(length=50), nullable=False),
    sa.Column('referans_id', sa.Integer(), nullable=False),
    sa.Column('talep_eden_id', sa.Integer(), nullable=False),
    sa.Column('talep_tarihi', sa.DateTime(), nullable=True),
    sa.Column('durum', sa.String(length=20), nullable=True),
    sa.Column('mevcut_adim', sa.Integer(), nullable=True),
    sa.Column('sonuc_tarihi', sa.DateTime(), nullable=True),
    sa.Column('sonuc_notu', sa.Text(), nullable=True),
    sa.Column('acil', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, default=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['akis_id'], ['onay_akislari.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['onay_tipi_id'], ['onay_tipleri.id'], ),
    sa.ForeignKeyConstraint(['talep_eden_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    # 6. onay_kayitlari (en son)
    op.create_table('onay_kayitlari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('talep_id', sa.Integer(), nullable=False),
    sa.Column('adim_id', sa.Integer(), nullable=False),
    sa.Column('onaylayici_id', sa.Integer(), nullable=True),
    sa.Column('vekil_mi', sa.Boolean(), nullable=True),
    sa.Column('asil_onaylayici_id', sa.Integer(), nullable=True),
    sa.Column('durum', sa.String(length=20), nullable=True),
    sa.Column('islem_tarihi', sa.DateTime(), nullable=True),
    sa.Column('not_', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['adim_id'], ['onay_adimlari.id'], ),
    sa.ForeignKeyConstraint(['asil_onaylayici_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['onaylayici_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['talep_id'], ['onay_talepleri.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('onay_kayitlari')
    op.drop_table('onay_talepleri')
    op.drop_table('yetki_devirleri')
    op.drop_table('onay_adimlari')
    op.drop_table('onay_akislari')
    op.drop_table('onay_tipleri')
    # ### end Alembic commands ###
