"""Add quiz models

Revision ID: 395cd719da95
Revises: 9ac3f15f1803
Create Date: 2025-12-31 13:08:32.268113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '395cd719da95'
down_revision = '9ac3f15f1803'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('soru_kategorileri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(length=100), nullable=False),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('ust_kategori_id', sa.Integer(), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('sira', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ust_kategori_id'], ['soru_kategorileri.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sorular',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('soru_metni', sa.Text(), nullable=False),
    sa.Column('soru_tipi', sa.String(length=20), nullable=True),
    sa.Column('kategori_id', sa.Integer(), nullable=True),
    sa.Column('egitim_tipi_id', sa.Integer(), nullable=True),
    sa.Column('zorluk', sa.Integer(), nullable=True),
    sa.Column('puan', sa.Integer(), nullable=True),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('gorsel_url', sa.String(length=500), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('olusturan_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['egitim_tipi_id'], ['egitim_tipleri.id'], ),
    sa.ForeignKeyConstraint(['kategori_id'], ['soru_kategorileri.id'], ),
    sa.ForeignKeyConstraint(['olusturan_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('soru_secenekleri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('soru_id', sa.Integer(), nullable=False),
    sa.Column('secenek_metni', sa.Text(), nullable=False),
    sa.Column('dogru', sa.Boolean(), nullable=True),
    sa.Column('sira', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['soru_id'], ['sorular.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('testler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('baslik', sa.String(length=200), nullable=False),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('egitim_id', sa.Integer(), nullable=True),
    sa.Column('egitim_tipi_id', sa.Integer(), nullable=True),
    sa.Column('sure_dakika', sa.Integer(), nullable=True),
    sa.Column('gecme_puani', sa.Integer(), nullable=True),
    sa.Column('soru_karistir', sa.Boolean(), nullable=True),
    sa.Column('secenek_karistir', sa.Boolean(), nullable=True),
    sa.Column('sonucu_goster', sa.Boolean(), nullable=True),
    sa.Column('dogru_cevaplari_goster', sa.Boolean(), nullable=True),
    sa.Column('tekrar_hak', sa.Integer(), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('baslangic_tarihi', sa.DateTime(), nullable=True),
    sa.Column('bitis_tarihi', sa.DateTime(), nullable=True),
    sa.Column('olusturan_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['egitim_id'], ['egitimler.id'], ),
    sa.ForeignKeyConstraint(['egitim_tipi_id'], ['egitim_tipleri.id'], ),
    sa.ForeignKeyConstraint(['olusturan_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_sonuclari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('calisan_id', sa.Integer(), nullable=False),
    sa.Column('baslangic_zamani', sa.DateTime(), nullable=True),
    sa.Column('bitis_zamani', sa.DateTime(), nullable=True),
    sa.Column('gecen_sure_saniye', sa.Integer(), nullable=True),
    sa.Column('tamamlandi', sa.Boolean(), nullable=True),
    sa.Column('toplam_puan', sa.Integer(), nullable=True),
    sa.Column('alinan_puan', sa.Integer(), nullable=True),
    sa.Column('dogru_sayisi', sa.Integer(), nullable=True),
    sa.Column('yanlis_sayisi', sa.Integer(), nullable=True),
    sa.Column('bos_sayisi', sa.Integer(), nullable=True),
    sa.Column('yuzde', sa.Float(), nullable=True),
    sa.Column('gecti', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['calisan_id'], ['calisanlar.id'], ),
    sa.ForeignKeyConstraint(['test_id'], ['testler.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_sorulari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('soru_id', sa.Integer(), nullable=False),
    sa.Column('sira', sa.Integer(), nullable=True),
    sa.Column('ozel_puan', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['soru_id'], ['sorular.id'], ),
    sa.ForeignKeyConstraint(['test_id'], ['testler.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('test_id', 'soru_id', name='unique_test_soru')
    )
    op.create_table('test_cevaplari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sonuc_id', sa.Integer(), nullable=False),
    sa.Column('soru_id', sa.Integer(), nullable=False),
    sa.Column('secilen_secenek_id', sa.Integer(), nullable=True),
    sa.Column('secilen_secenekler', sa.JSON(), nullable=True),
    sa.Column('dogru', sa.Boolean(), nullable=True),
    sa.Column('alinan_puan', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['secilen_secenek_id'], ['soru_secenekleri.id'], ),
    sa.ForeignKeyConstraint(['sonuc_id'], ['test_sonuclari.id'], ),
    sa.ForeignKeyConstraint(['soru_id'], ['sorular.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sonuc_id', 'soru_id', name='unique_sonuc_soru')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_cevaplari')
    op.drop_table('test_sorulari')
    op.drop_table('test_sonuclari')
    op.drop_table('testler')
    op.drop_table('soru_secenekleri')
    op.drop_table('sorular')
    op.drop_table('soru_kategorileri')
    # ### end Alembic commands ###
