"""Add satinalma module

Revision ID: 4cd216b40c9b
Revises: 08520dd686a9
Create Date: 2026-01-04 12:41:31.297641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cd216b40c9b'
down_revision = '08520dd686a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('satinalma_kategorileri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(length=100), nullable=False),
    sa.Column('kod', sa.String(length=20), nullable=True),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('ikon', sa.String(length=50), nullable=True),
    sa.Column('onay_limiti', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('sira', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kod')
    )
    op.create_table('satinalma_talepleri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('talep_no', sa.String(length=20), nullable=True),
    sa.Column('talep_eden_id', sa.Integer(), nullable=False),
    sa.Column('departman', sa.String(length=100), nullable=True),
    sa.Column('kategori_id', sa.Integer(), nullable=True),
    sa.Column('baslik', sa.String(length=200), nullable=False),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('gerekce', sa.Text(), nullable=True),
    sa.Column('oncelik', sa.String(length=20), nullable=True),
    sa.Column('talep_tarihi', sa.Date(), nullable=True),
    sa.Column('istenen_tarih', sa.Date(), nullable=True),
    sa.Column('tahmini_tutar', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('para_birimi', sa.String(length=3), nullable=True),
    sa.Column('proje_id', sa.Integer(), nullable=True),
    sa.Column('durum', sa.String(length=20), nullable=True),
    sa.Column('onay_talebi_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['kategori_id'], ['satinalma_kategorileri.id'], ),
    sa.ForeignKeyConstraint(['onay_talebi_id'], ['onay_talepleri.id'], ),
    sa.ForeignKeyConstraint(['proje_id'], ['projeler.id'], ),
    sa.ForeignKeyConstraint(['talep_eden_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('talep_no')
    )
    op.create_table('satinalma_teklifleri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('talep_id', sa.Integer(), nullable=False),
    sa.Column('tedarikci_id', sa.Integer(), nullable=False),
    sa.Column('teklif_no', sa.String(length=50), nullable=True),
    sa.Column('teklif_tarihi', sa.Date(), nullable=True),
    sa.Column('gecerlilik_tarihi', sa.Date(), nullable=True),
    sa.Column('toplam_tutar', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('para_birimi', sa.String(length=3), nullable=True),
    sa.Column('kdv_dahil', sa.Boolean(), nullable=True),
    sa.Column('teslimat_suresi', sa.String(length=50), nullable=True),
    sa.Column('teslimat_notu', sa.Text(), nullable=True),
    sa.Column('odeme_kosulu', sa.String(length=100), nullable=True),
    sa.Column('durum', sa.String(length=20), nullable=True),
    sa.Column('notlar', sa.Text(), nullable=True),
    sa.Column('dosya_adi', sa.String(length=255), nullable=True),
    sa.Column('dosya_yolu', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['talep_id'], ['satinalma_talepleri.id'], ),
    sa.ForeignKeyConstraint(['tedarikci_id'], ['tedarikciler.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('talep_kalemleri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('talep_id', sa.Integer(), nullable=False),
    sa.Column('urun_adi', sa.String(length=200), nullable=False),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('miktar', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('birim', sa.String(length=20), nullable=True),
    sa.Column('birim_fiyat', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('tutar', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['talep_id'], ['satinalma_talepleri.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('satinalma_siparisleri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('siparis_no', sa.String(length=20), nullable=True),
    sa.Column('talep_id', sa.Integer(), nullable=False),
    sa.Column('teklif_id', sa.Integer(), nullable=True),
    sa.Column('tedarikci_id', sa.Integer(), nullable=False),
    sa.Column('siparis_tarihi', sa.Date(), nullable=True),
    sa.Column('beklenen_teslimat', sa.Date(), nullable=True),
    sa.Column('toplam_tutar', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('para_birimi', sa.String(length=3), nullable=True),
    sa.Column('durum', sa.String(length=20), nullable=True),
    sa.Column('notlar', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['talep_id'], ['satinalma_talepleri.id'], ),
    sa.ForeignKeyConstraint(['tedarikci_id'], ['tedarikciler.id'], ),
    sa.ForeignKeyConstraint(['teklif_id'], ['satinalma_teklifleri.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('siparis_no')
    )
    op.create_table('teklif_kalemleri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teklif_id', sa.Integer(), nullable=False),
    sa.Column('talep_kalemi_id', sa.Integer(), nullable=True),
    sa.Column('urun_adi', sa.String(length=200), nullable=False),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('miktar', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('birim', sa.String(length=20), nullable=True),
    sa.Column('birim_fiyat', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tutar', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['talep_kalemi_id'], ['talep_kalemleri.id'], ),
    sa.ForeignKeyConstraint(['teklif_id'], ['satinalma_teklifleri.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('siparis_teslimatlari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('siparis_id', sa.Integer(), nullable=False),
    sa.Column('teslimat_tarihi', sa.Date(), nullable=False),
    sa.Column('teslim_alan_id', sa.Integer(), nullable=True),
    sa.Column('irsaliye_no', sa.String(length=50), nullable=True),
    sa.Column('notlar', sa.Text(), nullable=True),
    sa.Column('dosya_adi', sa.String(length=255), nullable=True),
    sa.Column('dosya_yolu', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['siparis_id'], ['satinalma_siparisleri.id'], ),
    sa.ForeignKeyConstraint(['teslim_alan_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('siparis_teslimatlari')
    op.drop_table('teklif_kalemleri')
    op.drop_table('satinalma_siparisleri')
    op.drop_table('talep_kalemleri')
    op.drop_table('satinalma_teklifleri')
    op.drop_table('satinalma_talepleri')
    op.drop_table('satinalma_kategorileri')
    # ### end Alembic commands ###
