"""Add zimmet models

Revision ID: 4d10a4c33729
Revises: b5bc26f335ee
Create Date: 2025-12-19 20:33:49.966170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d10a4c33729'
down_revision = 'b5bc26f335ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zimmet_tipleri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(length=100), nullable=False),
    sa.Column('kod', sa.String(length=20), nullable=True),
    sa.Column('kategori', sa.String(length=50), nullable=True),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('seri_no_zorunlu', sa.Boolean(), nullable=True),
    sa.Column('iade_zorunlu', sa.Boolean(), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kod')
    )
    op.create_table('zimmetler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calisan_id', sa.Integer(), nullable=False),
    sa.Column('zimmet_tipi_id', sa.Integer(), nullable=False),
    sa.Column('tanim', sa.String(length=255), nullable=True),
    sa.Column('seri_no', sa.String(length=100), nullable=True),
    sa.Column('demirbas_no', sa.String(length=50), nullable=True),
    sa.Column('marka', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('teslim_tarihi', sa.Date(), nullable=False),
    sa.Column('teslim_eden_id', sa.Integer(), nullable=True),
    sa.Column('teslim_notu', sa.Text(), nullable=True),
    sa.Column('iade_tarihi', sa.Date(), nullable=True),
    sa.Column('iade_alan_id', sa.Integer(), nullable=True),
    sa.Column('iade_notu', sa.Text(), nullable=True),
    sa.Column('iade_durumu', sa.String(length=50), nullable=True),
    sa.Column('durum', sa.String(length=20), nullable=True),
    sa.Column('deger', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['calisan_id'], ['calisanlar.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['iade_alan_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['teslim_eden_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['zimmet_tipi_id'], ['zimmet_tipleri.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zimmet_loglar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zimmet_id', sa.Integer(), nullable=False),
    sa.Column('islem', sa.String(length=50), nullable=True),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('islem_yapan_id', sa.Integer(), nullable=True),
    sa.Column('eski_calisan_id', sa.Integer(), nullable=True),
    sa.Column('yeni_calisan_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['eski_calisan_id'], ['calisanlar.id'], ),
    sa.ForeignKeyConstraint(['islem_yapan_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['yeni_calisan_id'], ['calisanlar.id'], ),
    sa.ForeignKeyConstraint(['zimmet_id'], ['zimmetler.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zimmet_loglar')
    op.drop_table('zimmetler')
    op.drop_table('zimmet_tipleri')
    # ### end Alembic commands ###
