"""Disiplin ve Dava modelleri

Revision ID: 4f9e7a164f63
Revises: 653938e14ee0
Create Date: 2026-01-15 14:14:19.299897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f9e7a164f63'
down_revision = '653938e14ee0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('davalar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dosya_no', sa.String(length=50), nullable=True),
    sa.Column('esas_no', sa.String(length=50), nullable=True),
    sa.Column('mahkeme', sa.String(length=200), nullable=False),
    sa.Column('dava_turu', sa.String(length=100), nullable=False),
    sa.Column('davaci', sa.String(length=200), nullable=False),
    sa.Column('davali', sa.String(length=200), nullable=False),
    sa.Column('calisan_id', sa.Integer(), nullable=True),
    sa.Column('acilis_tarihi', sa.Date(), nullable=False),
    sa.Column('son_durusma', sa.Date(), nullable=True),
    sa.Column('sonraki_durusma', sa.Date(), nullable=True),
    sa.Column('karar_tarihi', sa.Date(), nullable=True),
    sa.Column('talep_tutari', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('karar_tutari', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('durum', sa.String(length=30), nullable=True),
    sa.Column('sonuc', sa.String(length=50), nullable=True),
    sa.Column('konu_ozeti', sa.Text(), nullable=True),
    sa.Column('notlar', sa.Text(), nullable=True),
    sa.Column('avukat', sa.String(length=200), nullable=True),
    sa.Column('avukat_telefon', sa.String(length=20), nullable=True),
    sa.Column('sorumlu_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['calisan_id'], ['calisanlar.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sorumlu_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dosya_no')
    )
    op.create_table('disiplin_kayitlari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calisan_id', sa.Integer(), nullable=False),
    sa.Column('tarih', sa.Date(), nullable=False),
    sa.Column('tur', sa.String(length=50), nullable=False),
    sa.Column('seviye', sa.Integer(), nullable=True),
    sa.Column('konu', sa.String(length=200), nullable=False),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('belge_path', sa.String(length=500), nullable=True),
    sa.Column('olusturan_id', sa.Integer(), nullable=True),
    sa.Column('onaylayan_id', sa.Integer(), nullable=True),
    sa.Column('onay_tarihi', sa.DateTime(), nullable=True),
    sa.Column('durum', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['calisan_id'], ['calisanlar.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['olusturan_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['onaylayan_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('disiplin_kayitlari')
    op.drop_table('davalar')
    # ### end Alembic commands ###
