"""MasrafRaporu modeli eklendi

Revision ID: 653938e14ee0
Revises: 818a1726be54
Create Date: 2026-01-14 20:02:39.309109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '653938e14ee0'
down_revision = '818a1726be54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('masraf_raporlari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calisan_id', sa.Integer(), nullable=False),
    sa.Column('donem_yil', sa.Integer(), nullable=False),
    sa.Column('donem_ay', sa.Integer(), nullable=False),
    sa.Column('baslik', sa.String(length=200), nullable=True),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('toplam_masraf', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('avans_tutari', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('net_odeme', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('durum', sa.String(length=20), nullable=True),
    sa.Column('onay_talebi_id', sa.Integer(), nullable=True),
    sa.Column('onaylayan_id', sa.Integer(), nullable=True),
    sa.Column('onay_tarihi', sa.DateTime(), nullable=True),
    sa.Column('onay_notu', sa.Text(), nullable=True),
    sa.Column('odeme_tarihi', sa.Date(), nullable=True),
    sa.Column('odeme_referans', sa.String(length=100), nullable=True),
    sa.Column('yonetici_mail_gonderildi', sa.Boolean(), nullable=True),
    sa.Column('muhasebe_mail_gonderildi', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['calisan_id'], ['calisanlar.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['onay_talebi_id'], ['onay_talepleri.id'], ),
    sa.ForeignKeyConstraint(['onaylayan_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('masraf_raporu_kalemleri',
    sa.Column('rapor_id', sa.Integer(), nullable=False),
    sa.Column('masraf_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['masraf_id'], ['masraflar.id'], ),
    sa.ForeignKeyConstraint(['rapor_id'], ['masraf_raporlari.id'], ),
    sa.PrimaryKeyConstraint('rapor_id', 'masraf_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('masraf_raporu_kalemleri')
    op.drop_table('masraf_raporlari')
    # ### end Alembic commands ###
