"""Add masraf module

Revision ID: 7165106eb187
Revises: 361e72e046a3
Create Date: 2026-01-04 11:30:12.588435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7165106eb187'
down_revision = '361e72e046a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('masraf_kategorileri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(length=100), nullable=False),
    sa.Column('kod', sa.String(length=20), nullable=True),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('ikon', sa.String(length=50), nullable=True),
    sa.Column('renk', sa.String(length=20), nullable=True),
    sa.Column('gunluk_limit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('aylik_limit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fatura_zorunlu', sa.Boolean(), nullable=True),
    sa.Column('muhasebe_kodu', sa.String(length=50), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('sira', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kod')
    )
    op.create_table('masraf_avanslari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calisan_id', sa.Integer(), nullable=False),
    sa.Column('tutar', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('para_birimi', sa.String(length=3), nullable=True),
    sa.Column('tarih', sa.Date(), nullable=False),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('proje_id', sa.Integer(), nullable=True),
    sa.Column('durum', sa.String(length=20), nullable=True),
    sa.Column('kullanilan_tutar', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['calisan_id'], ['calisanlar.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['proje_id'], ['projeler.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('masraflar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calisan_id', sa.Integer(), nullable=False),
    sa.Column('baslik', sa.String(length=200), nullable=False),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('masraf_tarihi', sa.Date(), nullable=False),
    sa.Column('donem_ay', sa.Integer(), nullable=True),
    sa.Column('donem_yil', sa.Integer(), nullable=True),
    sa.Column('kategori_id', sa.Integer(), nullable=True),
    sa.Column('tutar', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('kdv_orani', sa.Integer(), nullable=True),
    sa.Column('kdv_tutari', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('toplam_tutar', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('para_birimi', sa.String(length=3), nullable=True),
    sa.Column('kur', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('tl_karsiligi', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('proje_id', sa.Integer(), nullable=True),
    sa.Column('fatura_no', sa.String(length=50), nullable=True),
    sa.Column('fatura_tarihi', sa.Date(), nullable=True),
    sa.Column('firma_adi', sa.String(length=200), nullable=True),
    sa.Column('firma_vkn', sa.String(length=20), nullable=True),
    sa.Column('dosya_adi', sa.String(length=255), nullable=True),
    sa.Column('dosya_yolu', sa.String(length=500), nullable=True),
    sa.Column('dosya_tipi', sa.String(length=50), nullable=True),
    sa.Column('ocr_yapildi', sa.Boolean(), nullable=True),
    sa.Column('ocr_ham_veri', sa.JSON(), nullable=True),
    sa.Column('durum', sa.String(length=20), nullable=True),
    sa.Column('odeme_tarihi', sa.Date(), nullable=True),
    sa.Column('odeme_referans', sa.String(length=100), nullable=True),
    sa.Column('onay_talebi_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['calisan_id'], ['calisanlar.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['kategori_id'], ['masraf_kategorileri.id'], ),
    sa.ForeignKeyConstraint(['onay_talebi_id'], ['onay_talepleri.id'], ),
    sa.ForeignKeyConstraint(['proje_id'], ['projeler.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('masraf_kalemleri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('masraf_id', sa.Integer(), nullable=False),
    sa.Column('aciklama', sa.String(length=500), nullable=False),
    sa.Column('miktar', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('birim_fiyat', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tutar', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('kdv_orani', sa.Integer(), nullable=True),
    sa.Column('kdv_tutari', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('kategori_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['kategori_id'], ['masraf_kategorileri.id'], ),
    sa.ForeignKeyConstraint(['masraf_id'], ['masraflar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('onay_tipleri', schema=None) as batch_op:
        batch_op.add_column(sa.Column('varsayilan_akis_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'onay_akislari', ['varsayilan_akis_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('onay_tipleri', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('varsayilan_akis_id')

    op.drop_table('masraf_kalemleri')
    op.drop_table('masraflar')
    op.drop_table('masraf_avanslari')
    op.drop_table('masraf_kategorileri')
    # ### end Alembic commands ###
