"""Add depo tables

Revision ID: 794309d06a02
Revises: 2c7c919b2464
Create Date: 2026-01-15 14:46:10.812953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '794309d06a02'
down_revision = '2c7c919b2464'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('depolar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kod', sa.String(length=20), nullable=False),
    sa.Column('ad', sa.String(length=100), nullable=False),
    sa.Column('adres', sa.Text(), nullable=True),
    sa.Column('sorumlu_id', sa.Integer(), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('notlar', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sorumlu_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kod')
    )
    op.create_table('urun_kategorileri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(length=100), nullable=False),
    sa.Column('ust_kategori_id', sa.Integer(), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ust_kategori_id'], ['urun_kategorileri.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stok_hareketleri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hareket_no', sa.String(length=30), nullable=False),
    sa.Column('tarih', sa.DateTime(), nullable=False),
    sa.Column('tip', sa.String(length=20), nullable=False),
    sa.Column('depo_id', sa.Integer(), nullable=False),
    sa.Column('hedef_depo_id', sa.Integer(), nullable=True),
    sa.Column('taraf_tipi', sa.String(length=20), nullable=True),
    sa.Column('tedarikci_id', sa.Integer(), nullable=True),
    sa.Column('musteri_id', sa.Integer(), nullable=True),
    sa.Column('calisan_id', sa.Integer(), nullable=True),
    sa.Column('sirket_adi', sa.String(length=200), nullable=True),
    sa.Column('proje_id', sa.Integer(), nullable=True),
    sa.Column('belge_no', sa.String(length=50), nullable=True),
    sa.Column('belge_tarihi', sa.Date(), nullable=True),
    sa.Column('durum', sa.String(length=20), nullable=True),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('olusturan_id', sa.Integer(), nullable=True),
    sa.Column('onaylayan_id', sa.Integer(), nullable=True),
    sa.Column('onay_tarihi', sa.DateTime(), nullable=True),
    sa.Column('imza_data', sa.Text(), nullable=True),
    sa.Column('imzalayan_ad', sa.String(length=100), nullable=True),
    sa.Column('imza_tarihi', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['calisan_id'], ['calisanlar.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['depo_id'], ['depolar.id'], ),
    sa.ForeignKeyConstraint(['hedef_depo_id'], ['depolar.id'], ),
    sa.ForeignKeyConstraint(['musteri_id'], ['musteriler.id'], ),
    sa.ForeignKeyConstraint(['olusturan_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['onaylayan_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['proje_id'], ['projeler.id'], ),
    sa.ForeignKeyConstraint(['tedarikci_id'], ['tedarikciler.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hareket_no')
    )
    op.create_table('urunler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kod', sa.String(length=50), nullable=False),
    sa.Column('barkod', sa.String(length=50), nullable=True),
    sa.Column('ad', sa.String(length=200), nullable=False),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('kategori_id', sa.Integer(), nullable=True),
    sa.Column('birim', sa.String(length=20), nullable=True),
    sa.Column('alis_fiyati', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('satis_fiyati', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('min_stok', sa.Integer(), nullable=True),
    sa.Column('max_stok', sa.Integer(), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['kategori_id'], ['urun_kategorileri.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kod')
    )
    op.create_table('stok_hareketi_kalemleri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hareket_id', sa.Integer(), nullable=False),
    sa.Column('urun_id', sa.Integer(), nullable=False),
    sa.Column('miktar', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('birim_fiyat', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('seri_no', sa.String(length=100), nullable=True),
    sa.Column('lot_no', sa.String(length=100), nullable=True),
    sa.Column('son_kullanma', sa.Date(), nullable=True),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['hareket_id'], ['stok_hareketleri.id'], ),
    sa.ForeignKeyConstraint(['urun_id'], ['urunler.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stok_kartlari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('depo_id', sa.Integer(), nullable=False),
    sa.Column('urun_id', sa.Integer(), nullable=False),
    sa.Column('miktar', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('rezerve_miktar', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('proje_id', sa.Integer(), nullable=True),
    sa.Column('musteri_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['depo_id'], ['depolar.id'], ),
    sa.ForeignKeyConstraint(['musteri_id'], ['musteriler.id'], ),
    sa.ForeignKeyConstraint(['proje_id'], ['projeler.id'], ),
    sa.ForeignKeyConstraint(['urun_id'], ['urunler.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('depo_id', 'urun_id', 'proje_id', 'musteri_id', name='uq_stok_karti')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stok_kartlari')
    op.drop_table('stok_hareketi_kalemleri')
    op.drop_table('urunler')
    op.drop_table('stok_hareketleri')
    op.drop_table('urun_kategorileri')
    op.drop_table('depolar')
    # ### end Alembic commands ###
