"""Add egitim models

Revision ID: 9ac3f15f1803
Revises: 4d10a4c33729
Create Date: 2025-12-30 17:14:25.660167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ac3f15f1803'
down_revision = '4d10a4c33729'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('egitim_tipleri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(length=100), nullable=False),
    sa.Column('kod', sa.String(length=20), nullable=True),
    sa.Column('kategori', sa.String(length=50), nullable=True),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('sure_saat', sa.Float(), nullable=True),
    sa.Column('gecerlilik_gun', sa.Integer(), nullable=True),
    sa.Column('sertifika_gerekli', sa.Boolean(), nullable=True),
    sa.Column('tekrar_periyot_gun', sa.Integer(), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('sira', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kod')
    )
    op.create_table('calisan_zorunlu_egitimler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calisan_id', sa.Integer(), nullable=False),
    sa.Column('egitim_tipi_id', sa.Integer(), nullable=False),
    sa.Column('tamamlandi', sa.Boolean(), nullable=True),
    sa.Column('tamamlanma_tarihi', sa.Date(), nullable=True),
    sa.Column('son_gecerlilik', sa.Date(), nullable=True),
    sa.Column('hatirlatma_gonderildi', sa.Boolean(), nullable=True),
    sa.Column('hatirlatma_tarihi', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['calisan_id'], ['calisanlar.id'], ),
    sa.ForeignKeyConstraint(['egitim_tipi_id'], ['egitim_tipleri.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('calisan_id', 'egitim_tipi_id', name='unique_calisan_zorunlu_egitim')
    )
    op.create_table('egitimler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('egitim_tipi_id', sa.Integer(), nullable=False),
    sa.Column('baslik', sa.String(length=200), nullable=False),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('proje_id', sa.Integer(), nullable=True),
    sa.Column('baslangic_tarihi', sa.DateTime(), nullable=False),
    sa.Column('bitis_tarihi', sa.DateTime(), nullable=True),
    sa.Column('sure_saat', sa.Float(), nullable=True),
    sa.Column('lokasyon_tipi', sa.String(length=20), nullable=True),
    sa.Column('lokasyon', sa.String(length=200), nullable=True),
    sa.Column('egitmen_tipi', sa.String(length=20), nullable=True),
    sa.Column('egitmen_id', sa.Integer(), nullable=True),
    sa.Column('dis_egitmen_ad', sa.String(length=100), nullable=True),
    sa.Column('dis_egitmen_kurum', sa.String(length=200), nullable=True),
    sa.Column('kontenjan', sa.Integer(), nullable=True),
    sa.Column('min_katilimci', sa.Integer(), nullable=True),
    sa.Column('durum', sa.String(length=20), nullable=True),
    sa.Column('iptal_nedeni', sa.Text(), nullable=True),
    sa.Column('maliyet', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('para_birimi', sa.String(length=3), nullable=True),
    sa.Column('notlar', sa.Text(), nullable=True),
    sa.Column('olusturan_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['egitim_tipi_id'], ['egitim_tipleri.id'], ),
    sa.ForeignKeyConstraint(['egitmen_id'], ['calisanlar.id'], ),
    sa.ForeignKeyConstraint(['olusturan_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['proje_id'], ['projeler.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pozisyon_zorunlu_egitimler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pozisyon_id', sa.Integer(), nullable=True),
    sa.Column('kadro_id', sa.Integer(), nullable=True),
    sa.Column('egitim_tipi_id', sa.Integer(), nullable=False),
    sa.Column('zorunlu', sa.Boolean(), nullable=True),
    sa.Column('oncelik', sa.Integer(), nullable=True),
    sa.Column('sure_gun', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['egitim_tipi_id'], ['egitim_tipleri.id'], ),
    sa.ForeignKeyConstraint(['kadro_id'], ['hedef_kadrolar.id'], ),
    sa.ForeignKeyConstraint(['pozisyon_id'], ['pozisyonlar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('egitim_katilimcilar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('egitim_id', sa.Integer(), nullable=False),
    sa.Column('calisan_id', sa.Integer(), nullable=False),
    sa.Column('durum', sa.String(length=20), nullable=True),
    sa.Column('davet_tarihi', sa.DateTime(), nullable=True),
    sa.Column('davet_eden_id', sa.Integer(), nullable=True),
    sa.Column('katilim_tarihi', sa.DateTime(), nullable=True),
    sa.Column('katilim_notu', sa.Text(), nullable=True),
    sa.Column('puan', sa.Integer(), nullable=True),
    sa.Column('degerlendirme', sa.Text(), nullable=True),
    sa.Column('sertifika_no', sa.String(length=50), nullable=True),
    sa.Column('sertifika_tarihi', sa.Date(), nullable=True),
    sa.Column('sertifika_gecerlilik', sa.Date(), nullable=True),
    sa.Column('mazeret_nedeni', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['calisan_id'], ['calisanlar.id'], ),
    sa.ForeignKeyConstraint(['davet_eden_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['egitim_id'], ['egitimler.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('egitim_id', 'calisan_id', name='unique_egitim_katilimci')
    )
    op.create_table('egitim_materyalleri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('egitim_id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(length=200), nullable=False),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('materyal_tipi', sa.String(length=20), nullable=True),
    sa.Column('dosya_adi', sa.String(length=255), nullable=True),
    sa.Column('dosya_yolu', sa.String(length=500), nullable=True),
    sa.Column('dosya_boyut', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('harici_link', sa.String(length=500), nullable=True),
    sa.Column('sira', sa.Integer(), nullable=True),
    sa.Column('yukleyen_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['egitim_id'], ['egitimler.id'], ),
    sa.ForeignKeyConstraint(['yukleyen_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('egitim_materyalleri')
    op.drop_table('egitim_katilimcilar')
    op.drop_table('pozisyon_zorunlu_egitimler')
    op.drop_table('egitimler')
    op.drop_table('calisan_zorunlu_egitimler')
    op.drop_table('egitim_tipleri')
    # ### end Alembic commands ###
