"""Add evrak and isten cikis models

Revision ID: b5bc26f335ee
Revises: 
Create Date: 2025-12-19 20:03:59.980176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5bc26f335ee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evrak_tipleri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(length=100), nullable=False),
    sa.Column('kod', sa.String(length=20), nullable=True),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('zorunlu', sa.Boolean(), nullable=True),
    sa.Column('kategori', sa.String(length=50), nullable=True),
    sa.Column('gecerlilik_suresi', sa.Integer(), nullable=True),
    sa.Column('sira', sa.Integer(), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kod')
    )
    op.create_table('calisan_evraklar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calisan_id', sa.Integer(), nullable=False),
    sa.Column('evrak_tipi_id', sa.Integer(), nullable=False),
    sa.Column('dosya_adi', sa.String(length=255), nullable=True),
    sa.Column('dosya_yolu', sa.String(length=500), nullable=True),
    sa.Column('dosya_boyut', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('gecerlilik_bitis', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['calisan_id'], ['calisanlar.id'], ),
    sa.ForeignKeyConstraint(['evrak_tipi_id'], ['evrak_tipleri.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('isten_cikislar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calisan_id', sa.Integer(), nullable=False),
    sa.Column('talep_tarihi', sa.Date(), nullable=True),
    sa.Column('planlanan_cikis_tarihi', sa.Date(), nullable=False),
    sa.Column('gerceklesen_cikis_tarihi', sa.Date(), nullable=True),
    sa.Column('cikis_tipi', sa.String(length=30), nullable=True),
    sa.Column('cikis_sebebi', sa.String(length=100), nullable=True),
    sa.Column('detay_notu', sa.Text(), nullable=True),
    sa.Column('zimmet_teslim', sa.Boolean(), nullable=True),
    sa.Column('zimmet_notu', sa.Text(), nullable=True),
    sa.Column('sgk_cikis_bildirimi', sa.Boolean(), nullable=True),
    sa.Column('sgk_bildirim_tarihi', sa.Date(), nullable=True),
    sa.Column('kidem_tazminati', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('ihbar_tazminati', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('cikis_mulakati_yapildi', sa.Boolean(), nullable=True),
    sa.Column('cikis_mulakat_notu', sa.Text(), nullable=True),
    sa.Column('durum', sa.String(length=20), nullable=True),
    sa.Column('olusturan_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['calisan_id'], ['calisanlar.id'], ),
    sa.ForeignKeyConstraint(['olusturan_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aday_evraklar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aday_id', sa.Integer(), nullable=False),
    sa.Column('evrak_tipi_id', sa.Integer(), nullable=False),
    sa.Column('dosya_adi', sa.String(length=255), nullable=True),
    sa.Column('dosya_yolu', sa.String(length=500), nullable=True),
    sa.Column('dosya_boyut', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('durum', sa.String(length=20), nullable=True),
    sa.Column('red_sebebi', sa.Text(), nullable=True),
    sa.Column('yukleyen_id', sa.Integer(), nullable=True),
    sa.Column('onaylayan_id', sa.Integer(), nullable=True),
    sa.Column('onay_tarihi', sa.DateTime(), nullable=True),
    sa.Column('gecerlilik_bitis', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['aday_id'], ['adaylar.id'], ),
    sa.ForeignKeyConstraint(['evrak_tipi_id'], ['evrak_tipleri.id'], ),
    sa.ForeignKeyConstraint(['onaylayan_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['yukleyen_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aday_evraklar')
    op.drop_table('isten_cikislar')
    op.drop_table('calisan_evraklar')
    op.drop_table('evrak_tipleri')
    # ### end Alembic commands ###
