"""Add ayarlar module

Revision ID: b9a86d955720
Revises: 085b6b9ed5d8
Create Date: 2026-01-04 13:23:51.204492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9a86d955720'
down_revision = '085b6b9ed5d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sistem_ayarlari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kategori', sa.String(length=50), nullable=False),
    sa.Column('anahtar', sa.String(length=100), nullable=False),
    sa.Column('deger', sa.Text(), nullable=True),
    sa.Column('tip', sa.String(length=20), nullable=True),
    sa.Column('aciklama', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('anahtar')
    )
    op.create_table('aktivite_loglari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kullanici_id', sa.Integer(), nullable=True),
    sa.Column('eylem', sa.String(length=50), nullable=False),
    sa.Column('modul', sa.String(length=50), nullable=True),
    sa.Column('aciklama', sa.String(length=255), nullable=True),
    sa.Column('detay', sa.Text(), nullable=True),
    sa.Column('ip_adresi', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('tarih', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['kullanici_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aktivite_loglari')
    op.drop_table('sistem_ayarlari')
    # ### end Alembic commands ###
