"""Add filo teslim, kaza fotograf, ikame arac tables

Revision ID: e9086209810d
Revises: b9a86d955720
Create Date: 2026-01-05 19:26:36.274807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9086209810d'
down_revision = 'b9a86d955720'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_claims',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'permission_id')
    )
    op.create_table('arac_teslimler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('arac_id', sa.Integer(), nullable=False),
    sa.Column('islem_tipi', sa.String(length=20), nullable=False),
    sa.Column('tarih', sa.DateTime(), nullable=False),
    sa.Column('km', sa.Integer(), nullable=False),
    sa.Column('yakit_durumu', sa.String(length=20), nullable=True),
    sa.Column('teslim_eden_id', sa.Integer(), nullable=True),
    sa.Column('teslim_alan_id', sa.Integer(), nullable=True),
    sa.Column('teslim_eden_calisan_id', sa.Integer(), nullable=True),
    sa.Column('teslim_alan_calisan_id', sa.Integer(), nullable=True),
    sa.Column('aksesuarlar', sa.JSON(), nullable=True),
    sa.Column('mevcut_hasarlar', sa.Text(), nullable=True),
    sa.Column('yeni_hasar', sa.Boolean(), nullable=True),
    sa.Column('yeni_hasar_aciklama', sa.Text(), nullable=True),
    sa.Column('fotograflar', sa.JSON(), nullable=True),
    sa.Column('imza_teslim_eden', sa.Text(), nullable=True),
    sa.Column('imza_teslim_alan', sa.Text(), nullable=True),
    sa.Column('notlar', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['arac_id'], ['araclar.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['teslim_alan_calisan_id'], ['calisanlar.id'], ),
    sa.ForeignKeyConstraint(['teslim_alan_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['teslim_eden_calisan_id'], ['calisanlar.id'], ),
    sa.ForeignKeyConstraint(['teslim_eden_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ikame_araclar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asil_arac_id', sa.Integer(), nullable=False),
    sa.Column('plaka', sa.String(length=20), nullable=False),
    sa.Column('marka', sa.String(length=50), nullable=True),
    sa.Column('model', sa.String(length=50), nullable=True),
    sa.Column('baslangic_tarihi', sa.Date(), nullable=False),
    sa.Column('bitis_tarihi', sa.Date(), nullable=True),
    sa.Column('baslangic_km', sa.Integer(), nullable=True),
    sa.Column('bitis_km', sa.Integer(), nullable=True),
    sa.Column('tedarikci_id', sa.Integer(), nullable=True),
    sa.Column('gunluk_ucret', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('neden', sa.String(length=50), nullable=True),
    sa.Column('ilgili_kaza_id', sa.Integer(), nullable=True),
    sa.Column('durum', sa.String(length=20), nullable=True),
    sa.Column('notlar', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asil_arac_id'], ['araclar.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ilgili_kaza_id'], ['kazalar.id'], ),
    sa.ForeignKeyConstraint(['tedarikci_id'], ['tedarikciler.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kaza_fotograflar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kaza_id', sa.Integer(), nullable=False),
    sa.Column('dosya_adi', sa.String(length=255), nullable=False),
    sa.Column('dosya_yolu', sa.String(length=500), nullable=False),
    sa.Column('dosya_boyut', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('aciklama', sa.String(length=255), nullable=True),
    sa.Column('yukleyen_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['kaza_id'], ['kazalar.id'], ),
    sa.ForeignKeyConstraint(['yukleyen_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kazalar', schema=None) as batch_op:
        batch_op.add_column(sa.Column('onay_durumu', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('onaylayan_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('onay_tarihi', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('red_nedeni', sa.Text(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['onaylayan_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kazalar', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('red_nedeni')
        batch_op.drop_column('onay_tarihi')
        batch_op.drop_column('onaylayan_id')
        batch_op.drop_column('onay_durumu')

    op.drop_table('kaza_fotograflar')
    op.drop_table('ikame_araclar')
    op.drop_table('arac_teslimler')
    op.drop_table('user_claims')
    # ### end Alembic commands ###
