version = 5.2.2
archive_dir = /etc/letsencrypt/archive/portal.teamguerilla.com
cert = /etc/letsencrypt/live/portal.teamguerilla.com/cert.pem
privkey = /etc/letsencrypt/live/portal.teamguerilla.com/privkey.pem
chain = /etc/letsencrypt/live/portal.teamguerilla.com/chain.pem
fullchain = /etc/letsencrypt/live/portal.teamguerilla.com/fullchain.pem
[renewalparams]
account = 06963b9155e9f4ca396b308b10fdb8aa
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
portal.teamguerilla.com = /var/www/certbot
[acme_renewal_info]
ari_retry_after = 2026-04-17T08:23:11
